# File: .github/workflows/fetch-bus-data.yml
name: Fetch Bus Data

on:
  schedule:
    - cron: '* * * * *'  # Run every minute
  workflow_dispatch:     # Manual trigger for testing

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install requests
        
      - name: Fetch bus data
        env:
          API_TOKEN: ${{ secrets.SPTRANS_API_TOKEN }}
        run: python busp/scripts/fetch_bus_data.py
        
      - name: Commit and push if changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add data/
          timestamp=$(date +"%Y-%m-%d %H:%M:%S")
          git commit -m "Update bus data at $timestamp" || echo "No changes to commit"
          git push
